// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compress.proto

/*
Package compress is a generated protocol buffer package.

It is generated from these files:
	compress.proto

It has these top-level messages:
	CompressRequest
	CompressReply
*/
package compress

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 压缩类型
type Type int32

const (
	// GZIP BROTLI用于文本的压缩
	Type_GZIP   Type = 0
	Type_BROTLI Type = 1
	Type_WEBP   Type = 2
	Type_JPEG   Type = 3
	Type_PNG    Type = 4
)

var Type_name = map[int32]string{
	0: "GZIP",
	1: "BROTLI",
	2: "WEBP",
	3: "JPEG",
	4: "PNG",
}
var Type_value = map[string]int32{
	"GZIP":   0,
	"BROTLI": 1,
	"WEBP":   2,
	"JPEG":   3,
	"PNG":    4,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// The request message containing the user's name.
type CompressRequest struct {
	// 压缩类型
	Type Type `protobuf:"varint,1,opt,name=type,enum=compress.Type" json:"type,omitempty"`
	// 数据
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 压缩质量
	Quality uint32 `protobuf:"varint,7,opt,name=quality" json:"quality,omitempty"`
	// 图片类型
	ImageType string `protobuf:"bytes,8,opt,name=imageType" json:"imageType,omitempty"`
	// 图片宽度
	Width uint32 `protobuf:"varint,9,opt,name=width" json:"width,omitempty"`
	// 图片高度
	Height uint32 `protobuf:"varint,10,opt,name=height" json:"height,omitempty"`
}

func (m *CompressRequest) Reset()                    { *m = CompressRequest{} }
func (m *CompressRequest) String() string            { return proto.CompactTextString(m) }
func (*CompressRequest) ProtoMessage()               {}
func (*CompressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompressRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GZIP
}

func (m *CompressRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CompressRequest) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *CompressRequest) GetImageType() string {
	if m != nil {
		return m.ImageType
	}
	return ""
}

func (m *CompressRequest) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CompressRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// The response message containing the greetings
type CompressReply struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CompressReply) Reset()                    { *m = CompressReply{} }
func (m *CompressReply) String() string            { return proto.CompactTextString(m) }
func (*CompressReply) ProtoMessage()               {}
func (*CompressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CompressReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CompressRequest)(nil), "compress.CompressRequest")
	proto.RegisterType((*CompressReply)(nil), "compress.CompressReply")
	proto.RegisterEnum("compress.Type", Type_name, Type_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compress service

type CompressClient interface {
	// do compress
	Do(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressReply, error)
}

type compressClient struct {
	cc *grpc.ClientConn
}

func NewCompressClient(cc *grpc.ClientConn) CompressClient {
	return &compressClient{cc}
}

func (c *compressClient) Do(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressReply, error) {
	out := new(CompressReply)
	err := grpc.Invoke(ctx, "/compress.Compress/Do", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Compress service

type CompressServer interface {
	// do compress
	Do(context.Context, *CompressRequest) (*CompressReply, error)
}

func RegisterCompressServer(s *grpc.Server, srv CompressServer) {
	s.RegisterService(&_Compress_serviceDesc, srv)
}

func _Compress_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compress.Compress/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressServer).Do(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Compress_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compress.Compress",
	HandlerType: (*CompressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Compress_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compress.proto",
}

func init() { proto.RegisterFile("compress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0xbb, 0x6d, 0xfe, 0x4d, 0x32, 0xfc, 0x1b, 0x97, 0x41, 0x74, 0x15, 0x0f, 0x21, 0xbd,
	0x04, 0x0f, 0x3d, 0xd4, 0x93, 0x1e, 0xa3, 0x35, 0x54, 0x44, 0x97, 0xa5, 0x20, 0x78, 0x8b, 0xed,
	0xd2, 0x04, 0x52, 0xb3, 0x6d, 0xb6, 0x4a, 0x3e, 0x95, 0x5f, 0x51, 0xb2, 0x36, 0x09, 0x88, 0xb7,
	0xf9, 0xbd, 0x99, 0x79, 0x3c, 0x66, 0xc0, 0x5b, 0x16, 0x1b, 0xb5, 0x93, 0x65, 0x39, 0x51, 0xbb,
	0x42, 0x17, 0xe8, 0x34, 0x1c, 0x7c, 0x11, 0x38, 0xba, 0x3d, 0x80, 0x90, 0xdb, 0xbd, 0x2c, 0x35,
	0x06, 0x60, 0xe9, 0x4a, 0x49, 0x46, 0x7c, 0x12, 0x7a, 0x53, 0x6f, 0xd2, 0x2e, 0x2f, 0x2a, 0x25,
	0x85, 0xe9, 0x21, 0x82, 0xb5, 0x4a, 0x74, 0xc2, 0xfa, 0x3e, 0x09, 0xff, 0x0b, 0x53, 0x23, 0x03,
	0x7b, 0xbb, 0x4f, 0xf2, 0x4c, 0x57, 0xcc, 0xf6, 0x49, 0x38, 0x12, 0x0d, 0xe2, 0x05, 0xb8, 0xd9,
	0x26, 0x59, 0xcb, 0xda, 0x80, 0x39, 0x3e, 0x09, 0x5d, 0xd1, 0x09, 0x78, 0x0c, 0xff, 0x3e, 0xb3,
	0x95, 0x4e, 0x99, 0x6b, 0xb6, 0x7e, 0x00, 0x4f, 0x60, 0x98, 0xca, 0x6c, 0x9d, 0x6a, 0x06, 0x46,
	0x3e, 0x50, 0x30, 0x86, 0x51, 0x17, 0x58, 0xe5, 0x55, 0x1b, 0x85, 0x74, 0x51, 0x2e, 0xaf, 0xc1,
	0x32, 0xd6, 0x0e, 0x58, 0xf1, 0xeb, 0x9c, 0xd3, 0x1e, 0x02, 0x0c, 0x23, 0xf1, 0xbc, 0x78, 0x9c,
	0x53, 0x52, 0xab, 0x2f, 0xb3, 0x88, 0xd3, 0x7e, 0x5d, 0x3d, 0xf0, 0x59, 0x4c, 0x07, 0x68, 0xc3,
	0x80, 0x3f, 0xc5, 0xd4, 0x9a, 0xde, 0x83, 0xd3, 0xf8, 0xe3, 0x0d, 0xf4, 0xef, 0x0a, 0x3c, 0xeb,
	0x2e, 0xf0, 0xeb, 0x54, 0xe7, 0xa7, 0x7f, 0xb5, 0x54, 0x5e, 0x05, 0xbd, 0x68, 0x0c, 0xf4, 0x23,
	0x5b, 0x26, 0xef, 0x65, 0xd1, 0xce, 0x44, 0x6d, 0x72, 0x5e, 0xbf, 0x81, 0x93, 0xb7, 0xa1, 0xf9,
	0xc7, 0xd5, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc2, 0x37, 0x9a, 0x59, 0xa1, 0x01, 0x00, 0x00,
}
