// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compress.proto

/*
Package compress is a generated protocol buffer package.

It is generated from these files:
	compress.proto

It has these top-level messages:
	CompressRequest
	CompressReply
*/
package compress

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 压缩类型
type Type int32

const (
	// GZIP BROTLI用于文本的压缩
	Type_GZIP    Type = 0
	Type_BROTLI  Type = 1
	Type_JPEG    Type = 2
	Type_PNG     Type = 3
	Type_WEBP    Type = 4
	Type_GUETZLI Type = 5
)

var Type_name = map[int32]string{
	0: "GZIP",
	1: "BROTLI",
	2: "JPEG",
	3: "PNG",
	4: "WEBP",
	5: "GUETZLI",
}
var Type_value = map[string]int32{
	"GZIP":    0,
	"BROTLI":  1,
	"JPEG":    2,
	"PNG":     3,
	"WEBP":    4,
	"GUETZLI": 5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClipType int32

const (
	ClipType_NONE   ClipType = 0
	ClipType_CENTER ClipType = 1
	ClipType_LT     ClipType = 2
	ClipType_TC     ClipType = 3
)

var ClipType_name = map[int32]string{
	0: "NONE",
	1: "CENTER",
	2: "LT",
	3: "TC",
}
var ClipType_value = map[string]int32{
	"NONE":   0,
	"CENTER": 1,
	"LT":     2,
	"TC":     3,
}

func (x ClipType) String() string {
	return proto.EnumName(ClipType_name, int32(x))
}
func (ClipType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

// The request message containing the user's name.
type CompressRequest struct {
	// 压缩类型
	Type Type `protobuf:"varint,1,opt,name=type,enum=compress.Type" json:"type,omitempty"`
	// 数据
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 剪辑类型
	ClipType ClipType `protobuf:"varint,3,opt,name=clipType,enum=compress.ClipType" json:"clipType,omitempty"`
	// 压缩质量
	Quality uint32 `protobuf:"varint,7,opt,name=quality" json:"quality,omitempty"`
	// 图片类型
	ImageType Type `protobuf:"varint,8,opt,name=imageType,enum=compress.Type" json:"imageType,omitempty"`
	// 图片宽度
	Width uint32 `protobuf:"varint,9,opt,name=width" json:"width,omitempty"`
	// 图片高度
	Height uint32 `protobuf:"varint,10,opt,name=height" json:"height,omitempty"`
}

func (m *CompressRequest) Reset()                    { *m = CompressRequest{} }
func (m *CompressRequest) String() string            { return proto.CompactTextString(m) }
func (*CompressRequest) ProtoMessage()               {}
func (*CompressRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CompressRequest) GetType() Type {
	if m != nil {
		return m.Type
	}
	return Type_GZIP
}

func (m *CompressRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *CompressRequest) GetClipType() ClipType {
	if m != nil {
		return m.ClipType
	}
	return ClipType_NONE
}

func (m *CompressRequest) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *CompressRequest) GetImageType() Type {
	if m != nil {
		return m.ImageType
	}
	return Type_GZIP
}

func (m *CompressRequest) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *CompressRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// The response message containing the greetings
type CompressReply struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *CompressReply) Reset()                    { *m = CompressReply{} }
func (m *CompressReply) String() string            { return proto.CompactTextString(m) }
func (*CompressReply) ProtoMessage()               {}
func (*CompressReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CompressReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*CompressRequest)(nil), "compress.CompressRequest")
	proto.RegisterType((*CompressReply)(nil), "compress.CompressReply")
	proto.RegisterEnum("compress.Type", Type_name, Type_value)
	proto.RegisterEnum("compress.ClipType", ClipType_name, ClipType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compress service

type CompressClient interface {
	// do compress
	Do(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressReply, error)
}

type compressClient struct {
	cc *grpc.ClientConn
}

func NewCompressClient(cc *grpc.ClientConn) CompressClient {
	return &compressClient{cc}
}

func (c *compressClient) Do(ctx context.Context, in *CompressRequest, opts ...grpc.CallOption) (*CompressReply, error) {
	out := new(CompressReply)
	err := grpc.Invoke(ctx, "/compress.Compress/Do", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Compress service

type CompressServer interface {
	// do compress
	Do(context.Context, *CompressRequest) (*CompressReply, error)
}

func RegisterCompressServer(s *grpc.Server, srv CompressServer) {
	s.RegisterService(&_Compress_serviceDesc, srv)
}

func _Compress_Do_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CompressServer).Do(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compress.Compress/Do",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CompressServer).Do(ctx, req.(*CompressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Compress_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compress.Compress",
	HandlerType: (*CompressServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Do",
			Handler:    _Compress_Do_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compress.proto",
}

func init() { proto.RegisterFile("compress.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x41, 0x6f, 0xb2, 0x40,
	0x10, 0x75, 0x01, 0x01, 0xe7, 0xfb, 0xf4, 0xdb, 0x4c, 0xbe, 0xb4, 0xb4, 0x27, 0x83, 0x17, 0x63,
	0x1a, 0xd3, 0xd8, 0x5b, 0x8f, 0x50, 0x24, 0x36, 0x06, 0x09, 0xa1, 0x69, 0xe2, 0x8d, 0x2a, 0x51,
	0x12, 0x2c, 0xab, 0xac, 0x6d, 0xf8, 0xd5, 0xfd, 0x0b, 0x0d, 0xab, 0x40, 0x9b, 0x78, 0xda, 0x7d,
	0x33, 0xef, 0xbd, 0xcc, 0xdb, 0x1d, 0xe8, 0xad, 0xb2, 0x1d, 0x3b, 0xc4, 0x79, 0x3e, 0x66, 0x87,
	0x8c, 0x67, 0xa8, 0x57, 0xd8, 0xfc, 0x22, 0xf0, 0xcf, 0x3e, 0x83, 0x20, 0xde, 0x1f, 0xe3, 0x9c,
	0xa3, 0x09, 0x0a, 0x2f, 0x58, 0x6c, 0x90, 0x3e, 0x19, 0xf6, 0x26, 0xbd, 0x71, 0x2d, 0x0e, 0x0b,
	0x16, 0x07, 0xa2, 0x87, 0x08, 0xca, 0x3a, 0xe2, 0x91, 0x21, 0xf5, 0xc9, 0xf0, 0x6f, 0x20, 0xee,
	0x38, 0x06, 0x7d, 0x95, 0x26, 0xac, 0x64, 0x19, 0xb2, 0xd0, 0x62, 0xa3, 0xb5, 0xcf, 0x9d, 0xa0,
	0xe6, 0xa0, 0x01, 0xda, 0xfe, 0x18, 0xa5, 0x09, 0x2f, 0x0c, 0xad, 0x4f, 0x86, 0xdd, 0xa0, 0x82,
	0x78, 0x07, 0x9d, 0x64, 0x17, 0x6d, 0x62, 0x61, 0xa5, 0x5f, 0x1c, 0xa3, 0x21, 0xe0, 0x7f, 0x68,
	0x7f, 0x26, 0x6b, 0xbe, 0x35, 0x3a, 0xc2, 0xe5, 0x04, 0xf0, 0x0a, 0xd4, 0x6d, 0x9c, 0x6c, 0xb6,
	0xdc, 0x00, 0x51, 0x3e, 0x23, 0x73, 0x00, 0xdd, 0x26, 0x30, 0x4b, 0x8b, 0x3a, 0x0a, 0x69, 0xa2,
	0x8c, 0xa6, 0xa0, 0x08, 0x6b, 0x1d, 0x14, 0x77, 0x39, 0xf3, 0x69, 0x0b, 0x01, 0x54, 0x2b, 0x58,
	0x84, 0xf3, 0x19, 0x25, 0x65, 0xf5, 0xd9, 0x77, 0x5c, 0x2a, 0xa1, 0x06, 0xb2, 0xef, 0xb9, 0x54,
	0x2e, 0x4b, 0xaf, 0x8e, 0xe5, 0x53, 0x05, 0xff, 0x80, 0xe6, 0xbe, 0x38, 0xe1, 0x72, 0x3e, 0xa3,
	0xed, 0xd1, 0x3d, 0xe8, 0x55, 0xf0, 0x92, 0xe2, 0x2d, 0x3c, 0xe7, 0xe4, 0x65, 0x3b, 0x5e, 0xe8,
	0x04, 0x94, 0xa0, 0x0a, 0xd2, 0x3c, 0xa4, 0x52, 0x79, 0x86, 0x36, 0x95, 0x27, 0x53, 0xd0, 0xab,
	0xf1, 0xf0, 0x11, 0xa4, 0xa7, 0x0c, 0x6f, 0x7e, 0x3c, 0xe2, 0xef, 0x9f, 0xba, 0xbd, 0xbe, 0xd4,
	0x62, 0x69, 0x61, 0xb6, 0xac, 0x01, 0xd0, 0x8f, 0x64, 0x15, 0xbd, 0xe7, 0x59, 0xcd, 0xb1, 0xea,
	0xe0, 0x7e, 0xb9, 0x05, 0x3e, 0x79, 0x53, 0xc5, 0x3a, 0x3c, 0x7c, 0x07, 0x00, 0x00, 0xff, 0xff,
	0xcd, 0x40, 0xe7, 0xbb, 0x20, 0x02, 0x00, 0x00,
}
