// Code generated by protoc-gen-go. DO NOT EDIT.
// source: optim.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UNKNOWN Type = 0
	Type_GZIP    Type = 1
	Type_BR      Type = 2
	Type_JPEG    Type = 3
	Type_PNG     Type = 4
	Type_WEBP    Type = 5
)

var Type_name = map[int32]string{
	0: "UNKNOWN",
	1: "GZIP",
	2: "BR",
	3: "JPEG",
	4: "PNG",
	5: "WEBP",
}

var Type_value = map[string]int32{
	"UNKNOWN": 0,
	"GZIP":    1,
	"BR":      2,
	"JPEG":    3,
	"PNG":     4,
	"WEBP":    5,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{0}
}

// The request message for optim
type OptimRequest struct {
	// 数据类型
	Source Type   `protobuf:"varint,1,opt,name=source,proto3,enum=pb.Type" json:"source,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 输出类型
	Output               Type     `protobuf:"varint,6,opt,name=output,proto3,enum=pb.Type" json:"output,omitempty"`
	Quality              uint32   `protobuf:"varint,7,opt,name=quality,proto3" json:"quality,omitempty"`
	Width                uint32   `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptimRequest) Reset()         { *m = OptimRequest{} }
func (m *OptimRequest) String() string { return proto.CompactTextString(m) }
func (*OptimRequest) ProtoMessage()    {}
func (*OptimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{0}
}

func (m *OptimRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimRequest.Unmarshal(m, b)
}
func (m *OptimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimRequest.Marshal(b, m, deterministic)
}
func (m *OptimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimRequest.Merge(m, src)
}
func (m *OptimRequest) XXX_Size() int {
	return xxx_messageInfo_OptimRequest.Size(m)
}
func (m *OptimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OptimRequest proto.InternalMessageInfo

func (m *OptimRequest) GetSource() Type {
	if m != nil {
		return m.Source
	}
	return Type_UNKNOWN
}

func (m *OptimRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OptimRequest) GetOutput() Type {
	if m != nil {
		return m.Output
	}
	return Type_UNKNOWN
}

func (m *OptimRequest) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *OptimRequest) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *OptimRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

// The response message for optim
type OptimReply struct {
	Output               Type     `protobuf:"varint,1,opt,name=output,proto3,enum=pb.Type" json:"output,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Width                uint32   `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptimReply) Reset()         { *m = OptimReply{} }
func (m *OptimReply) String() string { return proto.CompactTextString(m) }
func (*OptimReply) ProtoMessage()    {}
func (*OptimReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{1}
}

func (m *OptimReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OptimReply.Unmarshal(m, b)
}
func (m *OptimReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OptimReply.Marshal(b, m, deterministic)
}
func (m *OptimReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimReply.Merge(m, src)
}
func (m *OptimReply) XXX_Size() int {
	return xxx_messageInfo_OptimReply.Size(m)
}
func (m *OptimReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimReply.DiscardUnknown(m)
}

var xxx_messageInfo_OptimReply proto.InternalMessageInfo

func (m *OptimReply) GetOutput() Type {
	if m != nil {
		return m.Output
	}
	return Type_UNKNOWN
}

func (m *OptimReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OptimReply) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *OptimReply) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Type", Type_name, Type_value)
	proto.RegisterType((*OptimRequest)(nil), "pb.OptimRequest")
	proto.RegisterType((*OptimReply)(nil), "pb.OptimReply")
}

func init() { proto.RegisterFile("optim.proto", fileDescriptor_b0f4449489fcc4ff) }

var fileDescriptor_b0f4449489fcc4ff = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x4a, 0xf3, 0x40,
	0x14, 0x86, 0x3b, 0x69, 0xfe, 0xbe, 0xd3, 0x7e, 0x65, 0x38, 0x88, 0x0c, 0xae, 0x42, 0x56, 0x41,
	0x30, 0x8b, 0x0a, 0x5e, 0x40, 0xb0, 0x04, 0x15, 0xd2, 0x10, 0x94, 0x82, 0xbb, 0xc4, 0x06, 0x13,
	0x88, 0xcc, 0xb4, 0x9d, 0x41, 0x72, 0x53, 0x5e, 0xa3, 0xcc, 0x24, 0x42, 0x10, 0x5d, 0xb8, 0x3b,
	0xef, 0x03, 0x67, 0xde, 0x87, 0x39, 0xb0, 0xe0, 0x42, 0xb6, 0x6f, 0xb1, 0x38, 0x72, 0xc9, 0xd1,
	0x12, 0x55, 0xf8, 0x41, 0x60, 0xb9, 0xd5, 0xac, 0xa8, 0x0f, 0xaa, 0x3e, 0x49, 0x0c, 0xc0, 0x3d,
	0x71, 0x75, 0x7c, 0xa9, 0x19, 0x09, 0x48, 0xb4, 0x5a, 0xfb, 0xb1, 0xa8, 0xe2, 0xc7, 0x5e, 0xd4,
	0xc5, 0xc8, 0x11, 0xc1, 0xde, 0x97, 0xb2, 0x64, 0x56, 0x40, 0xa2, 0x65, 0x61, 0x66, 0xbd, 0xc5,
	0x95, 0x14, 0x4a, 0x32, 0xf7, 0xfb, 0xd6, 0xc0, 0x91, 0x81, 0x77, 0x50, 0x65, 0xd7, 0xca, 0x9e,
	0x79, 0x01, 0x89, 0xfe, 0x17, 0x5f, 0x11, 0xcf, 0xc0, 0x79, 0x6f, 0xf7, 0xb2, 0x61, 0xbe, 0xe1,
	0x43, 0xc0, 0x73, 0x70, 0x9b, 0xba, 0x7d, 0x6d, 0x24, 0xfb, 0x67, 0xf0, 0x98, 0x42, 0x01, 0x30,
	0xfa, 0x8a, 0xae, 0x9f, 0xf4, 0x92, 0x5f, 0x7a, 0x7f, 0xb2, 0xfd, 0x53, 0xe3, 0x65, 0x02, 0xb6,
	0x7e, 0x11, 0x17, 0xe0, 0x3d, 0x65, 0x0f, 0xd9, 0x76, 0x97, 0xd1, 0x19, 0xfa, 0x60, 0xa7, 0xcf,
	0x77, 0x39, 0x25, 0xe8, 0x82, 0x95, 0x14, 0xd4, 0xd2, 0xe4, 0x3e, 0xdf, 0xa4, 0x74, 0x8e, 0x1e,
	0xcc, 0xf3, 0x2c, 0xa5, 0xb6, 0x46, 0xbb, 0x4d, 0x92, 0x53, 0x67, 0x7d, 0x03, 0x8e, 0xb1, 0xc6,
	0x2b, 0xf0, 0x6e, 0xf9, 0x30, 0x52, 0xed, 0x3a, 0xfd, 0xfb, 0x8b, 0xd5, 0x84, 0x88, 0xae, 0x0f,
	0x67, 0x95, 0x6b, 0x2e, 0x75, 0xfd, 0x19, 0x00, 0x00, 0xff, 0xff, 0x19, 0x77, 0x4c, 0x8e, 0xb8,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OptimClient is the client API for Optim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OptimClient interface {
	DoOptim(ctx context.Context, in *OptimRequest, opts ...grpc.CallOption) (*OptimReply, error)
}

type optimClient struct {
	cc *grpc.ClientConn
}

func NewOptimClient(cc *grpc.ClientConn) OptimClient {
	return &optimClient{cc}
}

func (c *optimClient) DoOptim(ctx context.Context, in *OptimRequest, opts ...grpc.CallOption) (*OptimReply, error) {
	out := new(OptimReply)
	err := c.cc.Invoke(ctx, "/pb.Optim/DoOptim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimServer is the server API for Optim service.
type OptimServer interface {
	DoOptim(context.Context, *OptimRequest) (*OptimReply, error)
}

// UnimplementedOptimServer can be embedded to have forward compatible implementations.
type UnimplementedOptimServer struct {
}

func (*UnimplementedOptimServer) DoOptim(ctx context.Context, req *OptimRequest) (*OptimReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoOptim not implemented")
}

func RegisterOptimServer(s *grpc.Server, srv OptimServer) {
	s.RegisterService(&_Optim_serviceDesc, srv)
}

func _Optim_DoOptim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimServer).DoOptim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Optim/DoOptim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimServer).DoOptim(ctx, req.(*OptimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Optim_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Optim",
	HandlerType: (*OptimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoOptim",
			Handler:    _Optim_DoOptim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optim.proto",
}
