// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: optim.proto

package pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Type int32

const (
	Type_UNKNOWN Type = 0
	Type_GZIP    Type = 1
	Type_BR      Type = 2
	// snappy
	Type_SNAPPY Type = 3
	// lz4
	Type_LZ4 Type = 4
	// zstd
	Type_ZSTD Type = 5
	Type_JPEG Type = 11
	Type_PNG  Type = 12
	Type_WEBP Type = 13
)

var Type_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "GZIP",
	2:  "BR",
	3:  "SNAPPY",
	4:  "LZ4",
	5:  "ZSTD",
	11: "JPEG",
	12: "PNG",
	13: "WEBP",
}

var Type_value = map[string]int32{
	"UNKNOWN": 0,
	"GZIP":    1,
	"BR":      2,
	"SNAPPY":  3,
	"LZ4":     4,
	"ZSTD":    5,
	"JPEG":    11,
	"PNG":     12,
	"WEBP":    13,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}

func (Type) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{0}
}

// The request message for optim
type OptimRequest struct {
	// 数据类型
	Source Type   `protobuf:"varint,1,opt,name=source,proto3,enum=pb.Type" json:"source,omitempty"`
	Data   []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// 输出类型
	Output  Type   `protobuf:"varint,6,opt,name=output,proto3,enum=pb.Type" json:"output,omitempty"`
	Quality uint32 `protobuf:"varint,7,opt,name=quality,proto3" json:"quality,omitempty"`
	Width   uint32 `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height  uint32 `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	// 裁剪类型
	Crop                 uint32   `protobuf:"varint,10,opt,name=crop,proto3" json:"crop,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptimRequest) Reset()         { *m = OptimRequest{} }
func (m *OptimRequest) String() string { return proto.CompactTextString(m) }
func (*OptimRequest) ProtoMessage()    {}
func (*OptimRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{0}
}
func (m *OptimRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptimRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptimRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptimRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimRequest.Merge(m, src)
}
func (m *OptimRequest) XXX_Size() int {
	return m.Size()
}
func (m *OptimRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimRequest.DiscardUnknown(m)
}

var xxx_messageInfo_OptimRequest proto.InternalMessageInfo

func (m *OptimRequest) GetSource() Type {
	if m != nil {
		return m.Source
	}
	return Type_UNKNOWN
}

func (m *OptimRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OptimRequest) GetOutput() Type {
	if m != nil {
		return m.Output
	}
	return Type_UNKNOWN
}

func (m *OptimRequest) GetQuality() uint32 {
	if m != nil {
		return m.Quality
	}
	return 0
}

func (m *OptimRequest) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *OptimRequest) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *OptimRequest) GetCrop() uint32 {
	if m != nil {
		return m.Crop
	}
	return 0
}

// The response message for optim
type OptimReply struct {
	Output               Type     `protobuf:"varint,1,opt,name=output,proto3,enum=pb.Type" json:"output,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	Width                uint32   `protobuf:"varint,8,opt,name=width,proto3" json:"width,omitempty"`
	Height               uint32   `protobuf:"varint,9,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OptimReply) Reset()         { *m = OptimReply{} }
func (m *OptimReply) String() string { return proto.CompactTextString(m) }
func (*OptimReply) ProtoMessage()    {}
func (*OptimReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_b0f4449489fcc4ff, []int{1}
}
func (m *OptimReply) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *OptimReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_OptimReply.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *OptimReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OptimReply.Merge(m, src)
}
func (m *OptimReply) XXX_Size() int {
	return m.Size()
}
func (m *OptimReply) XXX_DiscardUnknown() {
	xxx_messageInfo_OptimReply.DiscardUnknown(m)
}

var xxx_messageInfo_OptimReply proto.InternalMessageInfo

func (m *OptimReply) GetOutput() Type {
	if m != nil {
		return m.Output
	}
	return Type_UNKNOWN
}

func (m *OptimReply) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *OptimReply) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *OptimReply) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func init() {
	proto.RegisterEnum("pb.Type", Type_name, Type_value)
	proto.RegisterType((*OptimRequest)(nil), "pb.OptimRequest")
	proto.RegisterType((*OptimReply)(nil), "pb.OptimReply")
}

func init() { proto.RegisterFile("optim.proto", fileDescriptor_b0f4449489fcc4ff) }

var fileDescriptor_b0f4449489fcc4ff = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0xcd, 0x6a, 0x3a, 0x31,
	0x14, 0xc5, 0xcd, 0x38, 0x66, 0xfc, 0x5f, 0x3f, 0x08, 0x97, 0x3f, 0x25, 0x74, 0x31, 0x0c, 0xae,
	0xa4, 0x50, 0x17, 0xb6, 0x74, 0x5f, 0x51, 0xa4, 0x1f, 0x8c, 0x61, 0xb4, 0x48, 0xdd, 0x8d, 0x3a,
	0xd4, 0x01, 0x4b, 0xa2, 0x66, 0x28, 0xf3, 0x26, 0x7d, 0x9e, 0xae, 0xba, 0xec, 0x23, 0x14, 0xfb,
	0x22, 0x25, 0xd1, 0x82, 0x94, 0x76, 0xd1, 0xdd, 0x39, 0xbf, 0xe4, 0x26, 0xe7, 0x70, 0xa1, 0x22,
	0x95, 0x4e, 0x1f, 0x5b, 0x6a, 0x2d, 0xb5, 0x44, 0x47, 0x4d, 0x1b, 0x2f, 0x04, 0xaa, 0x03, 0xc3,
	0xa2, 0x64, 0x95, 0x25, 0x1b, 0x8d, 0x01, 0xd0, 0x8d, 0xcc, 0xd6, 0xb3, 0x84, 0x93, 0x80, 0x34,
	0xeb, 0xed, 0x72, 0x4b, 0x4d, 0x5b, 0xa3, 0x5c, 0x25, 0xd1, 0x9e, 0x23, 0x82, 0x3b, 0x8f, 0x75,
	0xcc, 0x9d, 0x80, 0x34, 0xab, 0x91, 0xd5, 0x66, 0x4a, 0x66, 0x5a, 0x65, 0x9a, 0xd3, 0xef, 0x53,
	0x3b, 0x8e, 0x1c, 0xbc, 0x55, 0x16, 0x2f, 0x53, 0x9d, 0x73, 0x2f, 0x20, 0xcd, 0x5a, 0xf4, 0x65,
	0xf1, 0x3f, 0x94, 0x9e, 0xd2, 0xb9, 0x5e, 0xf0, 0xb2, 0xe5, 0x3b, 0x83, 0x47, 0x40, 0x17, 0x49,
	0xfa, 0xb0, 0xd0, 0xfc, 0x9f, 0xc5, 0x7b, 0x67, 0x7e, 0x9f, 0xad, 0xa5, 0xe2, 0x60, 0xa9, 0xd5,
	0x0d, 0x05, 0xb0, 0xef, 0xa0, 0x96, 0xf9, 0x41, 0x16, 0xf2, 0x4b, 0x96, 0x9f, 0x1a, 0xfc, 0x29,
	0xc5, 0x49, 0x0c, 0xae, 0x79, 0x11, 0x2b, 0xe0, 0xdd, 0x85, 0x37, 0xe1, 0x60, 0x1c, 0xb2, 0x02,
	0x96, 0xc1, 0xed, 0x4f, 0xae, 0x04, 0x23, 0x48, 0xc1, 0xe9, 0x44, 0xcc, 0x41, 0x00, 0x3a, 0x0c,
	0x2f, 0x85, 0xb8, 0x67, 0x45, 0xf4, 0xa0, 0x78, 0x3b, 0x39, 0x67, 0xae, 0xb9, 0x36, 0x19, 0x8e,
	0xba, 0xac, 0x64, 0xd4, 0xb5, 0xe8, 0xf5, 0x59, 0xc5, 0x1c, 0x8a, 0xb0, 0xcf, 0xaa, 0x06, 0x8d,
	0x7b, 0x1d, 0xc1, 0x6a, 0xed, 0x0b, 0x28, 0xd9, 0x52, 0x78, 0x0a, 0x5e, 0x57, 0xee, 0x24, 0x33,
	0x55, 0x0e, 0xd7, 0x75, 0x5c, 0x3f, 0x20, 0x6a, 0x99, 0x37, 0x0a, 0x1d, 0xf6, 0xba, 0xf5, 0xc9,
	0xdb, 0xd6, 0x27, 0xef, 0x5b, 0x9f, 0x3c, 0x7f, 0xf8, 0x85, 0x29, 0xb5, 0xeb, 0x3e, 0xfb, 0x0c,
	0x00, 0x00, 0xff, 0xff, 0x1a, 0xe7, 0xd0, 0x08, 0xfd, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// OptimClient is the client API for Optim service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type OptimClient interface {
	DoOptim(ctx context.Context, in *OptimRequest, opts ...grpc.CallOption) (*OptimReply, error)
}

type optimClient struct {
	cc *grpc.ClientConn
}

func NewOptimClient(cc *grpc.ClientConn) OptimClient {
	return &optimClient{cc}
}

func (c *optimClient) DoOptim(ctx context.Context, in *OptimRequest, opts ...grpc.CallOption) (*OptimReply, error) {
	out := new(OptimReply)
	err := c.cc.Invoke(ctx, "/pb.Optim/DoOptim", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OptimServer is the server API for Optim service.
type OptimServer interface {
	DoOptim(context.Context, *OptimRequest) (*OptimReply, error)
}

// UnimplementedOptimServer can be embedded to have forward compatible implementations.
type UnimplementedOptimServer struct {
}

func (*UnimplementedOptimServer) DoOptim(ctx context.Context, req *OptimRequest) (*OptimReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DoOptim not implemented")
}

func RegisterOptimServer(s *grpc.Server, srv OptimServer) {
	s.RegisterService(&_Optim_serviceDesc, srv)
}

func _Optim_DoOptim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OptimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OptimServer).DoOptim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Optim/DoOptim",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OptimServer).DoOptim(ctx, req.(*OptimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Optim_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Optim",
	HandlerType: (*OptimServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoOptim",
			Handler:    _Optim_DoOptim_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "optim.proto",
}

func (m *OptimRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptimRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptimRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Crop != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Crop))
		i--
		dAtA[i] = 0x50
	}
	if m.Height != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x48
	}
	if m.Width != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Width))
		i--
		dAtA[i] = 0x40
	}
	if m.Quality != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Quality))
		i--
		dAtA[i] = 0x38
	}
	if m.Output != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Output))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintOptim(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Source != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Source))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *OptimReply) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *OptimReply) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *OptimReply) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.XXX_unrecognized != nil {
		i -= len(m.XXX_unrecognized)
		copy(dAtA[i:], m.XXX_unrecognized)
	}
	if m.Height != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x48
	}
	if m.Width != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Width))
		i--
		dAtA[i] = 0x40
	}
	if len(m.Data) > 0 {
		i -= len(m.Data)
		copy(dAtA[i:], m.Data)
		i = encodeVarintOptim(dAtA, i, uint64(len(m.Data)))
		i--
		dAtA[i] = 0x12
	}
	if m.Output != 0 {
		i = encodeVarintOptim(dAtA, i, uint64(m.Output))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintOptim(dAtA []byte, offset int, v uint64) int {
	offset -= sovOptim(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *OptimRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Source != 0 {
		n += 1 + sovOptim(uint64(m.Source))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovOptim(uint64(l))
	}
	if m.Output != 0 {
		n += 1 + sovOptim(uint64(m.Output))
	}
	if m.Quality != 0 {
		n += 1 + sovOptim(uint64(m.Quality))
	}
	if m.Width != 0 {
		n += 1 + sovOptim(uint64(m.Width))
	}
	if m.Height != 0 {
		n += 1 + sovOptim(uint64(m.Height))
	}
	if m.Crop != 0 {
		n += 1 + sovOptim(uint64(m.Crop))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func (m *OptimReply) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Output != 0 {
		n += 1 + sovOptim(uint64(m.Output))
	}
	l = len(m.Data)
	if l > 0 {
		n += 1 + l + sovOptim(uint64(l))
	}
	if m.Width != 0 {
		n += 1 + sovOptim(uint64(m.Width))
	}
	if m.Height != 0 {
		n += 1 + sovOptim(uint64(m.Height))
	}
	if m.XXX_unrecognized != nil {
		n += len(m.XXX_unrecognized)
	}
	return n
}

func sovOptim(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozOptim(x uint64) (n int) {
	return sovOptim(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *OptimRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptim
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptimRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptimRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Source", wireType)
			}
			m.Source = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Source |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptim
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			m.Output = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Output |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Quality", wireType)
			}
			m.Quality = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Quality |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Crop", wireType)
			}
			m.Crop = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Crop |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOptim(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOptim
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOptim
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *OptimReply) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOptim
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: OptimReply: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: OptimReply: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Output", wireType)
			}
			m.Output = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Output |= Type(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Data", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOptim
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthOptim
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Data = append(m.Data[:0], dAtA[iNdEx:postIndex]...)
			if m.Data == nil {
				m.Data = []byte{}
			}
			iNdEx = postIndex
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Width", wireType)
			}
			m.Width = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Width |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipOptim(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOptim
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthOptim
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			m.XXX_unrecognized = append(m.XXX_unrecognized, dAtA[iNdEx:iNdEx+skippy]...)
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOptim(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOptim
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOptim
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthOptim
			}
			iNdEx += length
			if iNdEx < 0 {
				return 0, ErrInvalidLengthOptim
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOptim
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOptim(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
				if iNdEx < 0 {
					return 0, ErrInvalidLengthOptim
				}
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOptim = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOptim   = fmt.Errorf("proto: integer overflow")
)
